import ast
import re

def extract_json_from_response(response: str) -> str:
    """
    Extract the json object from a response generated by the LLM
    Args:
        response: the response
    Returns:
        json_object: python list of the extracted json object
    """
    json_pattern = re.compile(r"\{.*\}", re.DOTALL)
    json_object = json_pattern.findall(response)
    # print(json_object)
    if len(json_object) != 1:
        print(response)
        
        raise ValueError(
            "the response does not contain one json object with required format!"
        )

    try:
        json_obj = ast.literal_eval(json_object[0])
    except Exception:
        raise ValueError(
            "the response does not contain one json object with required format!"
        )
    return json_obj